### PR TITLE
Update OS to Rocky 8.8, GCC to 11.2.1, Python to 3.10.11

### PR DESCRIPTION
**Pull request by murraystevenson**
This updates the build container to a Rocky 8.8, GCC 11.2.1, Python 3.10.11, glibc 2.28 environment based on the ASWF's [ci-base:2023.2](https://hub.docker.com/layers/aswf/ci-base/2023.2/images/sha256-0b0e15231c8527d668e6ca1cf5fa9f9c502c6ead8b05efa6d4840ae53862d75d?context=explore) container.

This provides us with a base to start making VFX Platform 2023 aligned "beta" builds of Gaffer 1.4 alongside "stable" builds from the current `2.0.0` container. We anticipate this new container to be a bit of a moving target while we learn from testing the "beta" builds of Gaffer 1.4 produced from it, with these builds and the container intended to become "stable" for Gaffer 1.5.

I've left the documentation related package versions unchanged for now. From my initial build testing they haven't required updating, and it means fewer moving parts to deal with as part of this update. There are a few issues still to address with documentation builds in this container, but they are more screenshot and annotation related (theme/font differences appearing to cause misalignment of annotations applied in post-processing, and mesa/GL differences appearing to cause rendering glitches with the GafferBot).

### CODE REVIEW

**Comment by boberfly** [comment]
Looking good @murraystevenson ! The Boost/LLVM ones I think you may want to see if those extra libs get linked with `ldd` I might've discovered it only by running it on a vanilla Rocky 9.3 or Ubuntu 22.04.

I noticed Qt Wayland being removed, I'd like to have this enabled if possible. Is it to prevent the chance of it being used in a Wayland session instead of using xcb aka xwayland? I'm pretty sure the plugin backend is only linked at runtime if available so it shouldn't affect systems without Wayland.

I'll do a build against the new GafferHQ container soon. Cheers!

**Comment by johnhaddon** [comment]
LGTM. But I don't seem to be able to build https://github.com/GafferHQ/dependencies/pull/249 in the resulting container. I get this error :

```
/opt/aswf/dependencies-0540549-source/Qt/working/qt-everywhere-src-5.15.8/qtbase/bin/qvkgen: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

This ticket talks about things I don't understand, but seems to imply that it's because I'm running the container on an old host (Centos 7 in my case) : https://bugreports.qt.io/browse/QTBUG-72484. What host have you tested the container on?

**Comment by murraystevenson** [comment]
> What host have you tested the container on?

Huh, it does seem to be the combination of new glibc with the old kernel from the container host leading to trouble with the Qt build. I've been testing this container on a Fedora Workstation 39 host with a quite modern kernel, as well as within a Centos 7 container on the same host. Qt builds fine in the inception of the Rocky 8 container hosted in the Centos 7 container hosted in Fedora 39, but that's likely because all the containers are seeing the modern kernel from the base OS...

I've now tested in a Centos 7 VM hosting the Rocky 8 container and see the `qvkgen` issue, which makes sense as the VM would be isolated from the host so the Rocky 8 container will be seeing Centos 7's kernel. Running the same test within a Rocky 8 VM works as expected as it has a modern enough kernel.

The Ubuntu 20.04 hosts we run GitHub Actions on should have an even more modern kernel than Rocky 8, so I'd expect this to also work on CI (not that we do dependencies builds there due to the limited resources). It's just going to be tricky to run local GCC 11.2.1 dependencies builds on a Centos 7 host without using a VM unless we can find some way of patching Qt.

> I noticed Qt Wayland being removed, I'd like to have this enabled if possible

@boberfly the goal at present is to start from a common base between the Centos 7/GCC 9.3.1 and the Rocky 8/GCC 11.2.1 dependencies builds and get some end-to-end tests happening before we consider updating versions or introducing any more complexity. On the upside, this container should now give you the option of enabling Wayland in your own dependencies builds for testing. Wayland is not something on our current priority list and I think we'd feel more comfortable considering enabling it for Gaffer releases only after knowing that it is actually functional and stable.

**Comment by murraystevenson** [comment]
Merging in order to push this to the container registry to continue build testing.

**Comment by johnhaddon** [comment]
> It's just going to be tricky to run local GCC 11.2.1 dependencies builds on a Centos 7 host without using a VM unless we can find some way of patching Qt.

In one of the dark corners of the rabbit hole I went down yesterday, I did see a patch that basically hardcoded the results of the tests that Qt does for kernel features, so that could be an option. But I think maybe I'll just grapple with VMs for a bit, until I get my host OS upgraded.

**Pull request merged**
